### ISSUE TITLE
Missing tags for last releases

### ISSUE THREAD

**Issue by Zophar78** [roman-mueller/rmueller-cron#13]
Hello,
Seems you missed the tags for release v0.1.4, v0.1.5, v0.1.6 and v0.1.7.... Could you please add them (and update your release plans if any). I heavily use r10k to manage my environments, so tags are quite important for me. Cheers ;)
_git tag -a v0.1.4 e558e07e4f
git tag -a v0.1.5 2bb009c48
git tag -a v0.1.6 9946ed6c4c
git tag -a v0.1.7 bf3643d9f1a9_

**Comment by roman-mueller** [comment]
Hi, 

sorry about that, I totally forgot about the tags :(
I think I sorted it all out (only v0.1.6 is in the list below v0.1.5 and v0.1.4 for some reason).

Can you check if everything is OK now?

**Comment by Zophar78** [comment]
Perfect, at least i can fetch the tags aligned with the correct commits. Thanks.
